/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.jdablooms;

public class bytearray_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected bytearray_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(bytearray_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cdabloomsJNI.delete_bytearray_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(long value) {
    cdabloomsJNI.bytearray_t_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return cdabloomsJNI.bytearray_t_size_get(swigCPtr, this);
  }

  public void setArray(String value) {
    cdabloomsJNI.bytearray_t_array_set(swigCPtr, this, value);
  }

  public String getArray() {
    return cdabloomsJNI.bytearray_t_array_get(swigCPtr, this);
  }

  public bytearray_t() {
    this(cdabloomsJNI.new_bytearray_t(), true);
  }

}
