/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.jdablooms;

public class counting_bloom_header_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected counting_bloom_header_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(counting_bloom_header_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cdabloomsJNI.delete_counting_bloom_header_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    cdabloomsJNI.counting_bloom_header_t_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return cdabloomsJNI.counting_bloom_header_t_id_get(swigCPtr, this);
  }

  public void setCount(long value) {
    cdabloomsJNI.counting_bloom_header_t_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return cdabloomsJNI.counting_bloom_header_t_count_get(swigCPtr, this);
  }

  public void set_pad(long value) {
    cdabloomsJNI.counting_bloom_header_t__pad_set(swigCPtr, this, value);
  }

  public long get_pad() {
    return cdabloomsJNI.counting_bloom_header_t__pad_get(swigCPtr, this);
  }

  public counting_bloom_header_t() {
    this(cdabloomsJNI.new_counting_bloom_header_t(), true);
  }

}
