/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.jdablooms;

public class scaling_bloom_header_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected scaling_bloom_header_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(scaling_bloom_header_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cdabloomsJNI.delete_scaling_bloom_header_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMax_id(long value) {
    cdabloomsJNI.scaling_bloom_header_t_max_id_set(swigCPtr, this, value);
  }

  public long getMax_id() {
    return cdabloomsJNI.scaling_bloom_header_t_max_id_get(swigCPtr, this);
  }

  public void setMem_seqnum(long value) {
    cdabloomsJNI.scaling_bloom_header_t_mem_seqnum_set(swigCPtr, this, value);
  }

  public long getMem_seqnum() {
    return cdabloomsJNI.scaling_bloom_header_t_mem_seqnum_get(swigCPtr, this);
  }

  public void setDisk_seqnum(long value) {
    cdabloomsJNI.scaling_bloom_header_t_disk_seqnum_set(swigCPtr, this, value);
  }

  public long getDisk_seqnum() {
    return cdabloomsJNI.scaling_bloom_header_t_disk_seqnum_get(swigCPtr, this);
  }

  public scaling_bloom_header_t() {
    this(cdabloomsJNI.new_scaling_bloom_header_t(), true);
  }

}
