/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.jdablooms;

public class scaling_bloom_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected scaling_bloom_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(scaling_bloom_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cdabloomsJNI.delete_scaling_bloom_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(scaling_bloom_header_t value) {
    cdabloomsJNI.scaling_bloom_t_header_set(swigCPtr, this, scaling_bloom_header_t.getCPtr(value), value);
  }

  public scaling_bloom_header_t getHeader() {
    long cPtr = cdabloomsJNI.scaling_bloom_t_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new scaling_bloom_header_t(cPtr, false);
  }

  public void setCapacity(long value) {
    cdabloomsJNI.scaling_bloom_t_capacity_set(swigCPtr, this, value);
  }

  public long getCapacity() {
    return cdabloomsJNI.scaling_bloom_t_capacity_get(swigCPtr, this);
  }

  public void setNum_blooms(long value) {
    cdabloomsJNI.scaling_bloom_t_num_blooms_set(swigCPtr, this, value);
  }

  public long getNum_blooms() {
    return cdabloomsJNI.scaling_bloom_t_num_blooms_get(swigCPtr, this);
  }

  public void setNum_bytes(long value) {
    cdabloomsJNI.scaling_bloom_t_num_bytes_set(swigCPtr, this, value);
  }

  public long getNum_bytes() {
    return cdabloomsJNI.scaling_bloom_t_num_bytes_get(swigCPtr, this);
  }

  public void setError_rate(double value) {
    cdabloomsJNI.scaling_bloom_t_error_rate_set(swigCPtr, this, value);
  }

  public double getError_rate() {
    return cdabloomsJNI.scaling_bloom_t_error_rate_get(swigCPtr, this);
  }

  public void setFd(int value) {
    cdabloomsJNI.scaling_bloom_t_fd_set(swigCPtr, this, value);
  }

  public int getFd() {
    return cdabloomsJNI.scaling_bloom_t_fd_get(swigCPtr, this);
  }

  public void setBlooms(SWIGTYPE_p_p_counting_bloom_t value) {
    cdabloomsJNI.scaling_bloom_t_blooms_set(swigCPtr, this, SWIGTYPE_p_p_counting_bloom_t.getCPtr(value));
  }

  public SWIGTYPE_p_p_counting_bloom_t getBlooms() {
    long cPtr = cdabloomsJNI.scaling_bloom_t_blooms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_counting_bloom_t(cPtr, false);
  }

  public void setBitmap(bitmap_t value) {
    cdabloomsJNI.scaling_bloom_t_bitmap_set(swigCPtr, this, bitmap_t.getCPtr(value), value);
  }

  public bitmap_t getBitmap() {
    long cPtr = cdabloomsJNI.scaling_bloom_t_bitmap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new bitmap_t(cPtr, false);
  }

  public scaling_bloom_t() {
    this(cdabloomsJNI.new_scaling_bloom_t(), true);
  }

}
