/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


 /* Put header files here or function declarations like below */
#include "murmur.h"
#include "dablooms.h"
 

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_MurmurHash3_1x64_1128(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  uint32_t arg3 ;
  void *arg4 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (uint32_t)jarg3; 
  arg4 = *(void **)&jarg4; 
  MurmurHash3_x64_128((void const *)arg1,arg2,arg3,arg4);
}


SWIGEXPORT jstring JNICALL Java_com_github_jdablooms_cdabloomsJNI_dablooms_1version(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)dablooms_version();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_bytearray_1t_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  bytearray_t *arg1 = (bytearray_t *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bytearray_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_bytearray_1t_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  bytearray_t *arg1 = (bytearray_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bytearray_t **)&jarg1; 
  result =  ((arg1)->size);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_bytearray_1t_1array_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  bytearray_t *arg1 = (bytearray_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bytearray_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->array);
    if (arg2) {
      arg1->array = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->array, (const char *)arg2);
    } else {
      arg1->array = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_github_jdablooms_cdabloomsJNI_bytearray_1t_1array_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  bytearray_t *arg1 = (bytearray_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bytearray_t **)&jarg1; 
  result = (char *) ((arg1)->array);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1bytearray_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  bytearray_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (bytearray_t *)calloc(1, sizeof(bytearray_t));
  *(bytearray_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_delete_1bytearray_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bytearray_t *arg1 = (bytearray_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(bytearray_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_bitmap_1t_1bytes_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->bytes = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_bitmap_1t_1bytes_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  result =  ((arg1)->bytes);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_bitmap_1t_1array_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->array);
    if (arg2) {
      arg1->array = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->array, (const char *)arg2);
    } else {
      arg1->array = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_github_jdablooms_cdabloomsJNI_bitmap_1t_1array_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  result = (char *) ((arg1)->array);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1bitmap_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  bitmap_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (bitmap_t *)calloc(1, sizeof(bitmap_t));
  *(bitmap_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_delete_1bitmap_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(bitmap_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_bitmap_1resize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  size_t arg2 ;
  size_t arg3 ;
  bitmap_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (size_t)jarg3; 
  result = (bitmap_t *)bitmap_resize(arg1,arg2,arg3);
  *(bitmap_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1bitmap(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  bitmap_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  result = (bitmap_t *)new_bitmap(arg1);
  *(bitmap_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_bitmap_1increment(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  unsigned int arg2 ;
  long arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (long)jarg3; 
  result = (int)bitmap_increment(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_bitmap_1decrement(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  unsigned int arg2 ;
  long arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (long)jarg3; 
  result = (int)bitmap_decrement(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_bitmap_1check(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  unsigned int arg2 ;
  long arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (long)jarg3; 
  result = (int)bitmap_check(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_bitmap_1flush(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  result = (int)bitmap_flush(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_free_1bitmap(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  bitmap_t *arg1 = (bitmap_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(bitmap_t **)&jarg1; 
  free_bitmap(arg1);
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1header_1t_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  counting_bloom_header_t *arg1 = (counting_bloom_header_t *) 0 ;
  uint64_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_header_t **)&jarg1; 
  arg2 = (uint64_t)jarg2; 
  if (arg1) (arg1)->id = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1header_1t_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_header_t *arg1 = (counting_bloom_header_t *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_header_t **)&jarg1; 
  result = (uint64_t) ((arg1)->id);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1header_1t_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  counting_bloom_header_t *arg1 = (counting_bloom_header_t *) 0 ;
  uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_header_t **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->count = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1header_1t_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_header_t *arg1 = (counting_bloom_header_t *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_header_t **)&jarg1; 
  result = (uint32_t) ((arg1)->count);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1header_1t_1_1pad_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  counting_bloom_header_t *arg1 = (counting_bloom_header_t *) 0 ;
  uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_header_t **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->_pad = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1header_1t_1_1pad_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_header_t *arg1 = (counting_bloom_header_t *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_header_t **)&jarg1; 
  result = (uint32_t) ((arg1)->_pad);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1counting_1bloom_1header_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  counting_bloom_header_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (counting_bloom_header_t *)calloc(1, sizeof(counting_bloom_header_t));
  *(counting_bloom_header_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_delete_1counting_1bloom_1header_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  counting_bloom_header_t *arg1 = (counting_bloom_header_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(counting_bloom_header_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1header_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  counting_bloom_header_t *arg2 = (counting_bloom_header_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = *(counting_bloom_header_t **)&jarg2; 
  if (arg1) (arg1)->header = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1header_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  counting_bloom_header_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result = (counting_bloom_header_t *) ((arg1)->header);
  *(counting_bloom_header_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1capacity_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->capacity = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1capacity_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result = (unsigned int) ((arg1)->capacity);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1offset_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->offset = arg2;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1offset_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result = (long) ((arg1)->offset);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1counts_1per_1func_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->counts_per_func = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1counts_1per_1func_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result = (unsigned int) ((arg1)->counts_per_func);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1hashes_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  uint32_t *arg2 = (uint32_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = *(uint32_t **)&jarg2; 
  if (arg1) (arg1)->hashes = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1hashes_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  uint32_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result = (uint32_t *) ((arg1)->hashes);
  *(uint32_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1nfuncs_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->nfuncs = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1nfuncs_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result =  ((arg1)->nfuncs);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result =  ((arg1)->size);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1num_1bytes_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->num_bytes = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1num_1bytes_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result =  ((arg1)->num_bytes);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1error_1rate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->error_rate = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1error_1rate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result = (double) ((arg1)->error_rate);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1bitmap_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  bitmap_t *arg2 = (bitmap_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = *(bitmap_t **)&jarg2; 
  if (arg1) (arg1)->bitmap = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1t_1bitmap_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  bitmap_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result = (bitmap_t *) ((arg1)->bitmap);
  *(bitmap_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1counting_1bloom_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  counting_bloom_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (counting_bloom_t *)calloc(1, sizeof(counting_bloom_t));
  *(counting_bloom_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_delete_1counting_1bloom_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(counting_bloom_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_free_1counting_1bloom(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  result = (int)free_counting_bloom(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1counting_1bloom(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  double arg2 ;
  counting_bloom_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (double)jarg2; 
  result = (counting_bloom_t *)new_counting_bloom(arg1,arg2);
  *(counting_bloom_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1counting_1bloom_1from_1file(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  double arg2 ;
  char *arg3 = (char *) 0 ;
  counting_bloom_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (double)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (counting_bloom_t *)new_counting_bloom_from_file(arg1,arg2,(char const *)arg3);
  *(counting_bloom_t **)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  result = (int)counting_bloom_add(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1remove(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  result = (int)counting_bloom_remove(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_counting_1bloom_1check(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  counting_bloom_t *arg1 = (counting_bloom_t *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(counting_bloom_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  result = (int)counting_bloom_check(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1header_1t_1max_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  scaling_bloom_header_t *arg1 = (scaling_bloom_header_t *) 0 ;
  uint64_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_header_t **)&jarg1; 
  arg2 = (uint64_t)jarg2; 
  if (arg1) (arg1)->max_id = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1header_1t_1max_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_header_t *arg1 = (scaling_bloom_header_t *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_header_t **)&jarg1; 
  result = (uint64_t) ((arg1)->max_id);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1header_1t_1mem_1seqnum_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  scaling_bloom_header_t *arg1 = (scaling_bloom_header_t *) 0 ;
  uint64_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_header_t **)&jarg1; 
  arg2 = (uint64_t)jarg2; 
  if (arg1) (arg1)->mem_seqnum = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1header_1t_1mem_1seqnum_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_header_t *arg1 = (scaling_bloom_header_t *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_header_t **)&jarg1; 
  result = (uint64_t) ((arg1)->mem_seqnum);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1header_1t_1disk_1seqnum_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  scaling_bloom_header_t *arg1 = (scaling_bloom_header_t *) 0 ;
  uint64_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_header_t **)&jarg1; 
  arg2 = (uint64_t)jarg2; 
  if (arg1) (arg1)->disk_seqnum = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1header_1t_1disk_1seqnum_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_header_t *arg1 = (scaling_bloom_header_t *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_header_t **)&jarg1; 
  result = (uint64_t) ((arg1)->disk_seqnum);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1scaling_1bloom_1header_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  scaling_bloom_header_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (scaling_bloom_header_t *)calloc(1, sizeof(scaling_bloom_header_t));
  *(scaling_bloom_header_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_delete_1scaling_1bloom_1header_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  scaling_bloom_header_t *arg1 = (scaling_bloom_header_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(scaling_bloom_header_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1header_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  scaling_bloom_header_t *arg2 = (scaling_bloom_header_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = *(scaling_bloom_header_t **)&jarg2; 
  if (arg1) (arg1)->header = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1header_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  scaling_bloom_header_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (scaling_bloom_header_t *) ((arg1)->header);
  *(scaling_bloom_header_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1capacity_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->capacity = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1capacity_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (unsigned int) ((arg1)->capacity);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1num_1blooms_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->num_blooms = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1num_1blooms_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (unsigned int) ((arg1)->num_blooms);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1num_1bytes_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->num_bytes = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1num_1bytes_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result =  ((arg1)->num_bytes);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1error_1rate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->error_rate = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1error_1rate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (double) ((arg1)->error_rate);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1fd_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->fd = arg2;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1fd_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (int) ((arg1)->fd);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1blooms_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  counting_bloom_t **arg2 = (counting_bloom_t **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = *(counting_bloom_t ***)&jarg2; 
  if (arg1) (arg1)->blooms = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1blooms_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  counting_bloom_t **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (counting_bloom_t **) ((arg1)->blooms);
  *(counting_bloom_t ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1bitmap_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  bitmap_t *arg2 = (bitmap_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = *(bitmap_t **)&jarg2; 
  if (arg1) (arg1)->bitmap = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1t_1bitmap_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  bitmap_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (bitmap_t *) ((arg1)->bitmap);
  *(bitmap_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1scaling_1bloom_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  scaling_bloom_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (scaling_bloom_t *)calloc(1, sizeof(scaling_bloom_t));
  *(scaling_bloom_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_github_jdablooms_cdabloomsJNI_delete_1scaling_1bloom_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1scaling_1bloom(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  double arg2 ;
  scaling_bloom_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (double)jarg2; 
  result = (scaling_bloom_t *)new_scaling_bloom(arg1,arg2);
  *(scaling_bloom_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_new_1scaling_1bloom_1from_1file(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  double arg2 ;
  char *arg3 = (char *) 0 ;
  scaling_bloom_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (double)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (scaling_bloom_t *)new_scaling_bloom_from_file(arg1,arg2,(char const *)arg3);
  *(scaling_bloom_t **)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_free_1scaling_1bloom(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (int)free_scaling_bloom(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1count(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (long)scaling_bloom_count(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  uint64_t arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  arg4 = (uint64_t)jarg4; 
  result = (int)scaling_bloom_add(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1remove(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  uint64_t arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  arg4 = (uint64_t)jarg4; 
  result = (int)scaling_bloom_remove(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1check(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  result = (int)scaling_bloom_check(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1add_1bytes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2, jlong jarg3) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  bytearray_t arg2 ;
  uint64_t arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  {
    char* a = (*jenv)->GetByteArrayElements(jenv, jarg2, NULL);
    const size_t sz = (*jenv)->GetArrayLength(jenv, jarg2);
    arg2 = (bytearray_t) {
      sz,a
    };
  }
  arg3 = (uint64_t)jarg3; 
  result = (int)scaling_bloom_add_bytes(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    // Or use  0 instead of ABORT to keep changes if it was a copy
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (&arg2)->array, JNI_ABORT);
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1remove_1bytes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2, jlong jarg3) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  bytearray_t arg2 ;
  uint64_t arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  {
    char* a = (*jenv)->GetByteArrayElements(jenv, jarg2, NULL);
    const size_t sz = (*jenv)->GetArrayLength(jenv, jarg2);
    arg2 = (bytearray_t) {
      sz,a
    };
  }
  arg3 = (uint64_t)jarg3; 
  result = (int)scaling_bloom_remove_bytes(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    // Or use  0 instead of ABORT to keep changes if it was a copy
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (&arg2)->array, JNI_ABORT);
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1check_1bytes(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  bytearray_t arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  {
    char* a = (*jenv)->GetByteArrayElements(jenv, jarg2, NULL);
    const size_t sz = (*jenv)->GetArrayLength(jenv, jarg2);
    arg2 = (bytearray_t) {
      sz,a
    };
  }
  result = (int)scaling_bloom_check_bytes(arg1,arg2);
  jresult = (jint)result; 
  {
    // Or use  0 instead of ABORT to keep changes if it was a copy
    (*jenv)->ReleaseByteArrayElements(jenv, jarg2, (&arg2)->array, JNI_ABORT);
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1flush(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (int)scaling_bloom_flush(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1mem_1seqnum(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (uint64_t)scaling_bloom_mem_seqnum(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_github_jdablooms_cdabloomsJNI_scaling_1bloom_1disk_1seqnum(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  scaling_bloom_t *arg1 = (scaling_bloom_t *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(scaling_bloom_t **)&jarg1; 
  result = (uint64_t)scaling_bloom_disk_seqnum(arg1);
  jresult = (jlong)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

